<?php

namespace AppBundle\Repository;

/**
 * CategorieRecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRecipeRepository extends \Doctrine\ORM\EntityRepository
{
}
