<?php

namespace AppBundle\Repository;

/**
 * CostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CostRepository extends \Doctrine\ORM\EntityRepository
{
}
