<?php

namespace AppBundle\Repository;

/**
 * DifficultyLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DifficultyLevelRepository extends \Doctrine\ORM\EntityRepository
{
}
