<?php

namespace AppBundle\Repository;

/**
 * IngredientRecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRecipeRepository extends \Doctrine\ORM\EntityRepository
{
}
